### ISSUE TITLE
Questions about PCA dimensionality

### ISSUE THREAD

**Issue by machengcheng2016** [nblt/DLDR#1]
Greetings. Really solid work!
However, I've got a simple question. In [train_pbfgs.py](https://github.com/nblt/DLDR/blob/main/train_pbfgs.py#L158) and [train_psgd.py](https://github.com/nblt/DLDR/blob/main/train_psgd.py#L156), it seems that you do PCA on W with a (num_ckpts, len_params) shape. However, according to the implementation of sklearn.decomposition.PCA, it is the dimension of num_ckpts rather than len_params that be reduced. In my understanding, it is len_params (~0.2M) that should be reduced to realize the subspace training. Is this a bug?

**Comment by nblt** [comment]
Thanks for your question. I have replied to you in the previous emails you sent.
